unbind r
bind r source-file ~/.tmux.conf

set -g status-position top
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Fix tmux terminal tabs
set -g set-titles on
set -g set-titles-string "#S / #W"

# TPM plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
# fix vim-tmux-navigator keybindings
bind -n C-M-l send-keys clear C-m
bind e resize-pane -t %0 -y 20

# set vi-mode
set-window-option -g mode-keys vi

# automation
new
attach
split-pane -v
select-pane -t 0
split-pane -h
send-keys -t %0 C-l
send-keys -t %0 "nvtop" C-m
resize-pane -t %0 -y 13
send-keys -t %0 C-l
send-keys -t %2 "htop" C-m
send-keys -t %1 C-l
select-pane -t %1
send-keys -t %1 "fastfetch" C-m
# Automatically rename tmux session based on hostname and trailing IP
run-shell 'tmux rename-session "$(hostname)_$(hostname -I | awk "{print \$1}" | awk -F "." "{print \$NF}")"'

run '~/.tmux/plugins/tpm/tpm'

